---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f bike_page.html $DEPLOYPATH
    - /bin/cp -f coffee_page.html $DEPLOYPATH
    - /bin/cp -f send-form.php $DEPLOYPATH
